
services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "80:80"    # Map container port 80 to host port 80 (for public HTTP access)
    volumes:
      - .:/var/www/html:ro   # Read-only mount source code
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
