version: "3.8"

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
    volumes:
      - .:/var/www/html:ro
      - ./default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
      - ./start.sh:/start.sh
    command: ["/bin/sh", "/start.sh"]
    depends_on:
      - php-fpm
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
