services:
    app:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
        image: pgims/laravel-app
        container_name: laravel-app
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:80"
        depends_on:
            - web

    web:
        build:
            context: ./docker/web
            dockerfile: Dockerfile
        image: pgims/nginx
        container_name: webserver
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

